site_name: WebLabs by dontdoitno
nav:
  - Home: index.md
  - Labs:
    - "Lab 1": labs/lab1.md
    - "Lab 2": labs/lab2.md
    - "Lab 3": labs/lab3.md
    - "Lab 4": labs/lab4.md
theme:
    name: shadcn
    show_stargazers: False
    pygments_style:
      light: gotthard-light
      dark: stata-dark
markdown_extensions:
  - codehilite
  - admonition
